# DO NOT EDIT THIS FILE MANUALLY! Use `release update-releases-file`.
load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")

_PREDECESSOR_VERSION = "23.2.0-rc.1"
CONFIG_LINUX_AMD64 = "linux-amd64"
CONFIG_LINUX_ARM64 = "linux-arm64"
CONFIG_DARWIN_AMD64 = "darwin-10.9-amd64"
CONFIG_DARWIN_ARM64 = "darwin-11.0-arm64"
_CONFIGS = [
    (CONFIG_LINUX_AMD64, "9642352a55cf6bca2e1b9077292465a6094d27dd0f5bf1d4fd3ae5e157451dd4"),
    (CONFIG_LINUX_ARM64, "ade07d0856f185fb13c1d1c25043a7eb49a55915f78f4e17d1693af57ee74d44"),
    (CONFIG_DARWIN_AMD64, "85e3ec772e771f9068a0e5f18104bc879c12cba22259ee4324de5270b42e353b"),
    (CONFIG_DARWIN_ARM64, "6fb6f4af82bc6f023a46cafce903908e64b5bec961adf49bc4f669631002a32d"),
]

def _munge_name(s):
    return s.replace("-", "_").replace(".", "_")

def _repo_name(config_name):
    return "cockroach_binary_v{}_{}".format(
        _munge_name(_PREDECESSOR_VERSION),
        _munge_name(config_name))

def _file_name(config_name):
    return "cockroach-v{}.{}/cockroach".format(
        _PREDECESSOR_VERSION, config_name)

def target(config_name):
    return "@{}//:{}".format(_repo_name(config_name),
                             _file_name(config_name))

def cockroach_binaries_for_testing():
    for config in _CONFIGS:
        config_name, shasum = config
        file_name = _file_name(config_name)
        http_archive(
            name = _repo_name(config_name),
            build_file_content = """exports_files(["{}"])""".format(file_name),
            sha256 = shasum,
            urls = [
                "https://binaries.cockroachdb.com/{}".format(
                    file_name.removesuffix("/cockroach")) + ".tgz",
            ],
        )
